
// This file has been generated by the GUI designer. Do not modify.
namespace ImageTagger
{
	public partial class ThumpnailButton
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ImageTagger.ThumpnailButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ImageTagger.ThumpnailButton";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
