
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action directoryAction;

	private global::Gtk.VBox vboxMain;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.VPaned vpaned3;

	private global::Gtk.ScrolledWindow scrolledwindow6;

	private global::Gtk.Image imageMain;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.HBox hboxThumbnails;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, "<Alt>f");
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, "<Alt>q");
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.openAction, null);
		this.directoryAction = new global::Gtk.Action ("directoryAction", global::Mono.Unix.Catalog.GetString ("Open directory"), null, "gtk-directory");
		this.directoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open directory");
		w1.Add (this.directoryAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox ();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><menuitem name='directoryAction' action='directoryAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vboxMain.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.vpaned3 = new global::Gtk.VPaned ();
		this.vpaned3.CanFocus = true;
		this.vpaned3.Name = "vpaned3";
		this.vpaned3.Position = 582;
		// Container child vpaned3.Gtk.Paned+PanedChild
		this.scrolledwindow6 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow6.CanFocus = true;
		this.scrolledwindow6.Name = "scrolledwindow6";
		this.scrolledwindow6.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow6.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.imageMain = new global::Gtk.Image ();
		this.imageMain.Name = "imageMain";
		this.imageMain.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
		w3.Add (this.imageMain);
		this.scrolledwindow6.Add (w3);
		this.vpaned3.Add (this.scrolledwindow6);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned3[this.scrolledwindow6]));
		w6.Resize = false;
		// Container child vpaned3.Gtk.Paned+PanedChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w7 = new global::Gtk.Viewport ();
		w7.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport1.Gtk.Container+ContainerChild
		this.hboxThumbnails = new global::Gtk.HBox ();
		this.hboxThumbnails.Name = "hboxThumbnails";
		this.hboxThumbnails.Spacing = 6;
		w7.Add (this.hboxThumbnails);
		this.scrolledwindow1.Add (w7);
		this.vpaned3.Add (this.scrolledwindow1);
		this.vboxMain.Add (this.vpaned3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.vpaned3]));
		w11.Position = 1;
		this.Add (this.vboxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1148;
		this.DefaultHeight = 862;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.directoryAction.Activated += new global::System.EventHandler (this.OnDirectoryActionActivated);
	}
}
